CREATE TABLE chats
(
    id         BIGINT GENERATED ALWAYS AS IDENTITY,
    status     VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP   NOT NULL DEFAULT now()
);

ALTER TABLE chats
    ADD CONSTRAINT pk_chats PRIMARY KEY (id);